### ISSUE TITLE
Questions about Gradle File

### ISSUE THREAD

**Issue by Boodyahmedhamdy** [MostafaMohamed2002/Todo-Tracker-Compose#1]
## First, Congratulations for building this amazing app

i have several questions about the application but let's focus on `build.gradle.kts` file for app module:

1. in `plugins` block. why you imported in multiple lines instead of single line? is there any reason ?
```kotlin
alias(  
  libs  
  .plugins  
  .jetbrains  
  .kotlin  
  .android,  
)
```
2. why did you commented compose options ?
```kotlin
//    composeOptions {  
//        kotlinCompilerExtensionVersion = "1.5.1"  
//    }
```

I hope you find those questions meaningful and generously answer them. 
Thanks ❤

**Comment by MostafaMohamed2002** [comment]
Thank you for your kind words❤️
1- i was trying ktlint and it did this , i should configure it properly
2- there is no need to use `kotlinCompilerExtensionVersion` since i migrated to kotlin 2.0 
see [this ](https://medium.com/mobile-innovation-network/migrate-to-kotlin-2-0-with-6-easy-steps-b41a6bf68184)for more , let me know  if you have any other questions 😊

**Comment by Boodyahmedhamdy** [comment]
Thanks for this answer and the useful article. I am still in the revision phase so other questions are coming 😂. I will post them (God-Willing) on the same thread.
